POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}


### 토큰 만료 예외 발생
GET http://localhost:8080/member/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4Mjc5NjAyMCwiZXhwIjoxNzgyNzk2MzIwLCJrZXkiOiJ2YWx1ZSJ9.Atr5US64mECkeGuwkUqmHJMGHIZ_kHuz4iISeVxUbJc

### JWT 시그니쳐 일부분 지운 뒤에 요청 -> JWT 시그니쳐가 일치하지 않아 예외 발생
GET http://localhost:8080/member/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4Mjc5NzUxMiwiZXhwIjoxNzgyNzk3ODEyLCJrZXkiOiJ2YWx1ZSJ9.zG_f9z4n9AOC4DV4uqsDXjQaHt3OL5VIpwepXvY4b

### 토큰 없이 요청 보내기 -> CustomAuthenticationEntryPoint 에서 처리
GET http://localhost:8080/member/3

### 권한 문제 테스트 (인가문제)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user3",
  "password": "1234"
}

### 일반회원 토큰으로 admin 권한의 url에 요청보내기
GET http://localhost:8080/security/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMyIsImlhdCI6MTc4Mjc5ODM4MCwiZXhwIjoxNzgyNzk4NjgwLCJrZXkiOiJ2YWx1ZSJ9.S90g_FfISf1VYaGWlRe-UfN7UvqdyxkODVpQTMIUtHk

